title: Training materials for Nextflow and containers (WIP)

plugins:
  - jekyll-sitemap

collections:
   hands-on:
        output: true

defaults:
  -
    scope:
      path: "_hands-on"
    values:
      layout: "default"
